f1 = open("file1.txt","w")
f1.write("Text in file1")
f1.close()
f1 = open("file1.txt","r")
print("file1 content ; "+f1.read())
f1.seek(0,0)
f2 = open("file2.txt","w")
f2.write(f1.read())
f2.close()
f2 = open("file2.txt","r")
print("file2 content : "+f2.read())